import { findWeatherDescriptionByCode } from '.';
import { describe, it, expect } from 'vitest';

describe('findWeatherDescriptionByCode', () => {
  it('should return the correct weather description', () => {
    expect(findWeatherDescriptionByCode(113)).toStrictEqual(['113', 'Sunny']);
    expect(findWeatherDescriptionByCode(116)).toStrictEqual([
      '116',
      'PartlyCloudy',
    ]);
    expect(findWeatherDescriptionByCode(119)).toStrictEqual(['119', 'Cloudy']);
    expect(findWeatherDescriptionByCode(122)).toStrictEqual([
      '122',
      'VeryCloudy',
    ]);
    expect(findWeatherDescriptionByCode(143)).toStrictEqual(['143', 'Fog']);
    expect(findWeatherDescriptionByCode(176)).toStrictEqual([
      '176',
      'LightShowers',
    ]);
    expect(findWeatherDescriptionByCode(179)).toStrictEqual([
      '179',
      'LightSleetShowers',
    ]);
    expect(findWeatherDescriptionByCode(182)).toStrictEqual([
      '182',
      'LightSleet',
    ]);
    expect(findWeatherDescriptionByCode(185)).toStrictEqual([
      '185',
      'LightSleet',
    ]);
    expect(findWeatherDescriptionByCode(200)).toStrictEqual([
      '200',
      'ThunderyShowers',
    ]);
    expect(findWeatherDescriptionByCode(227)).toStrictEqual([
      '227',
      'LightSnow',
    ]);
    expect(findWeatherDescriptionByCode(230)).toStrictEqual([
      '230',
      'HeavySnow',
    ]);
    expect(findWeatherDescriptionByCode(248)).toStrictEqual(['248', 'Fog']);
    expect(findWeatherDescriptionByCode(260)).toStrictEqual(['260', 'Fog']);
    expect(findWeatherDescriptionByCode(263)).toStrictEqual([
      '263',
      'LightShowers',
    ]);
    expect(findWeatherDescriptionByCode(266)).toStrictEqual([
      '266',
      'LightRain',
    ]);
    expect(findWeatherDescriptionByCode(281)).toStrictEqual([
      '281',
      'LightSleet',
    ]);
    expect(findWeatherDescriptionByCode(284)).toStrictEqual([
      '284',
      'LightSleet',
    ]);
    expect(findWeatherDescriptionByCode(293)).toStrictEqual([
      '293',
      'LightRain',
    ]);
    expect(findWeatherDescriptionByCode(296)).toStrictEqual([
      '296',
      'LightRain',
    ]);
    expect(findWeatherDescriptionByCode(299)).toStrictEqual([
      '299',
      'HeavyShowers',
    ]);
    expect(findWeatherDescriptionByCode(302)).toStrictEqual([
      '302',
      'HeavyRain',
    ]);
    expect(findWeatherDescriptionByCode(305)).toStrictEqual([
      '305',
      'HeavyShowers',
    ]);
    expect(findWeatherDescriptionByCode(308)).toStrictEqual([
      '308',
      'HeavyRain',
    ]);
    expect(findWeatherDescriptionByCode(311)).toStrictEqual([
      '311',
      'LightSleet',
    ]);
    expect(findWeatherDescriptionByCode(314)).toStrictEqual([
      '314',
      'LightSleet',
    ]);
    expect(findWeatherDescriptionByCode(317)).toStrictEqual([
      '317',
      'LightSleet',
    ]);
    expect(findWeatherDescriptionByCode(320)).toStrictEqual([
      '320',
      'LightSnow',
    ]);
    expect(findWeatherDescriptionByCode(323)).toStrictEqual([
      '323',
      'LightSnowShowers',
    ]);
    expect(findWeatherDescriptionByCode(326)).toStrictEqual([
      '326',
      'LightSnowShowers',
    ]);
    expect(findWeatherDescriptionByCode(329)).toStrictEqual([
      '329',
      'HeavySnow',
    ]);
    expect(findWeatherDescriptionByCode(332)).toStrictEqual([
      '332',
      'HeavySnow',
    ]);
    expect(findWeatherDescriptionByCode(335)).toStrictEqual([
      '335',
      'HeavySnowShowers',
    ]);
    expect(findWeatherDescriptionByCode(338)).toStrictEqual([
      '338',
      'HeavySnow',
    ]);
    expect(findWeatherDescriptionByCode(350)).toStrictEqual([
      '350',
      'LightSleet',
    ]);
    expect(findWeatherDescriptionByCode(353)).toStrictEqual([
      '353',
      'LightShowers',
    ]);
    expect(findWeatherDescriptionByCode(356)).toStrictEqual([
      '356',
      'HeavyShowers',
    ]);
    expect(findWeatherDescriptionByCode(359)).toStrictEqual([
      '359',
      'HeavyRain',
    ]);
    expect(findWeatherDescriptionByCode(362)).toStrictEqual([
      '362',
      'LightSleetShowers',
    ]);
    expect(findWeatherDescriptionByCode(365)).toStrictEqual([
      '365',
      'LightSleetShowers',
    ]);
    expect(findWeatherDescriptionByCode(368)).toStrictEqual([
      '368',
      'LightSnowShowers',
    ]);
    expect(findWeatherDescriptionByCode(371)).toStrictEqual([
      '371',
      'HeavySnowShowers',
    ]);
    expect(findWeatherDescriptionByCode(374)).toStrictEqual([
      '374',
      'LightSleetShowers',
    ]);
    expect(findWeatherDescriptionByCode(377)).toStrictEqual([
      '377',
      'LightSleet',
    ]);
    expect(findWeatherDescriptionByCode(386)).toStrictEqual([
      '386',
      'ThunderyShowers',
    ]);
    expect(findWeatherDescriptionByCode(389)).toStrictEqual([
      '389',
      'ThunderyHeavyRain',
    ]);
    expect(findWeatherDescriptionByCode(392)).toStrictEqual([
      '392',
      'ThunderySnowShowers',
    ]);
    expect(findWeatherDescriptionByCode(395)).toStrictEqual([
      '395',
      'HeavySnowShowers',
    ]);
  });
});
